version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.15.3
      - image: circleci/mysql:5.7.28
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: fRiend_test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test