version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: echo "complete me"
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.15.3
        environment:
          NODE_ENV: CCi
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - build
      - lint
      - test