version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "build"
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run:
  test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - build
      - lint
      - test