version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "build"
  lint:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "lint"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  build_and_lint_and_test:
    jobs:
      - build
      - lint
      - test