version: 2
jobs:
  lint:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "lint"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test